tags:
- name: servers
  description: servers API
- name: users
  description: users API

paths:
# [GET] servers
  /servers:
    get:
      tags:
      - servers
      summary: 서버 목록을 불러옵니다
      parameters:
      - name: id
        in: path
        description: User Id
        required: true
      responses:
        200:
          description: 'OK'
        401:
          description: '유저 인증 실패'
        500:
          description: '서버오류'
# [GET] users
  /users:
    get:
      tags:
      - users
      summary: 서버 목록을 불러옵니다
      parameters:
      - name: id
        in: path
        description: User Id
        required: true
      responses:
        200:
          description: 'OK'
        401:
          description: '유저 인증 실패'
        500:
          description: '서버오류'

schemes:
 - https
 - http
